Repository JunoLab/Weave.jl, pull requests merged in 2020-06, with the labels that each got.

#350 Reworking format.jl
  .travis.yml
  Project.toml
  src/Weave.jl
  src/display_methods.jl
  src/format.jl
  src/formats.jl
  src/rendering/common.jl
  src/rendering/htmlformats.jl
  src/rendering/markdownformats.jl
  src/rendering/rendering.jl
  src/rendering/texformats.jl
  src/rendering/variousformats.jl
  src/run.jl
  src/types.jl
  templates/md2pdf.tpl
  test/formatter_test.jl
  test/test_chunk_options.jl
Labels: enhancement, refactor

#360 yet another clean up:
  src/cache.jl
  src/run.jl
  src/types.jl
Labels: refactor

#361 make `list_out_formats` return return just data structure
  src/Weave.jl
Labels: breaking change

#373 improve term result
  Project.toml
  src/Weave.jl
  src/config.jl
  src/run.jl
  test/documents/gadfly/gadfly_formats_test.md.js.svg.pandoc
  test/documents/gadfly/gadfly_formats_test.md.pdf.github
  test/documents/gadfly/gadfly_formats_test.md.png.github
  test/documents/gadfly/gadfly_formats_test.md.png.pandoc
  test/documents/gadfly/gadfly_formats_test.md.svg.github
  test/documents/gadfly/gadfly_formats_test.tex.pdf.tex
  test/documents/gadfly/gadfly_formats_test.tex.png.tex
  test/documents/gadfly/gadfly_formats_test.tex.ps.tex
  test/documents/gadfly/gadfly_formats_test.tex.tex.tex
  test/documents/gadfly_formats_test.jnw
  test/documents/gadfly_markdown_test.jmd
  test/documents/inline/markdown_beamer.html.ref
  test/documents/inline/markdown_beamer.tex.ref
  test/documents/plotsjl/plotsjl_test.jl
  test/documents/plotsjl/plotsjl_test.md.ref
  test/documents/plotsjl/plotsjl_test.tex.ref
  test/documents/plotsjl/plotsjl_test_gr.md.ref
  test/documents/plotsjl/plotsjl_test_gr.tex.ref
  test/documents/plotsjl_test.jmd
  test/documents/plotsjl_test_gr.jmd
  test/documents/tangle/chunk_options.jl.ref
  test/gadfly_formats.jl
  test/plotsjl_test.jl
  test/runtests.jl
Labels: bug, enhancement
